project:
  type: book

book:
  title: "THESIS TITLE"
  author: "Holland Stam"
  date: "April 1, 2022"
  chapters:
    - index.qmd
    - Chapter1/Chapter1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  echo: false
  warning: false
  freeze: auto
