project:
  type: book

book:
  title: "Quantifying Art Historical Narratives"
  author: "Holland Stam"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - Chapter1/Chapter1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  echo: false
  warning: false

